### ISSUE TITLE
Page Preview Doesn't work on New Pages (404)

### ISSUE THREAD

**Issue by peetah74** [egandalf/eGandalf.Epi.PagePreview#2]
As stated in title, when creating a new page, if you open preview you get a 404.  The workaround we have is that we would disable the page in search and remove it from navigation and publish that but was wondering if page preview can still work on a page that's never been published.

Thanks you

**Comment by peetah74** [comment]
Hello

Wondering if there was any update to this? 
Thank you for your time.

**Comment by egandalf** [comment]
Hey - sorry I missed this. Yeah, it's a known issue. Right now it builds off of the current page's URL and until it's been published at least once, it doesn't have one. Not sure yet how to fix but I will work on it when I can.

**Comment by peetah74** [comment]
thank you for the update.

**Comment by bmcdavid** [comment]
#3 Proposed fix for this problem, but requires using an interface not covered by Episerver semantic versioning.

**Comment by egandalf** [comment]
Version 2.2 with Brad's code merged uploaded to the nuget feed and pending approval. Read documentation before using.
